config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create]
  resources :secrets, only: [:index]
  resources :confirmations, only: [:new, :create]
  resources :secrets, only: [:index]

  get '/logout', to: 'sessions#destroy'

  root 'home#index'
end

app/models/user.rb
require 'phony_rails'

class User < ActiveRecord::Base
  has_secure_password

  validates :first_name,
            :last_name,
            :email,
            :phone_number,
            :password_digest, presence: true

  validates_uniqueness_of :email

  def confirm!
    self.confirmed = true
    save!
  end

  def pretty_phone_number
    phone_number.phony_formatted(format: :international, spaces: ' ')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticated?
    session[:user_id] && session[:authenticated]
  end

  def authenticate!
    redirect_to new_session_path and return unless authenticated?
  end

  helper_method :authenticated?
end

app/controllers/confirmation_controller.rb
class ConfirmationController < ApplicationController
  def new
    @user = User.find(session[:user_id])
  end

  def create
    @user = User.find params[:user_id]
    if @user.verification_code == params[:verification_code]
      @user.update(confirmed: true)
      session[:authenticated] = true
      redirect_to secrets_path
    else
      flash[:error] = "Verification code is incorrect."
      render :new
    end
  end
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < ApplicationController
  def new
    @user = User.find(session[:user_id])
  end

  def create
    @user = User.find params[:user_id]
    if @user.verification_code == params[:verification_code]
      @user.confirm!
      session[:authenticated] = true

      flash[:notice] = "Welcome #{@user.first_name}. The Adventure Begins!"
      redirect_to secrets_path
    else
      flash.now[:error] = "Verification code is incorrect."
      render :new
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/secrets_controller.rb
class SecretsController < ApplicationController
  before_action :authenticate!

  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      session[:authenticated] = false
      ConfirmationSender.send_confirmation_to @user

      redirect_to new_confirmation_path
    else
      flash.now[:error] = "Wrong user/password."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    session[:authenticated] = nil
    flash.now[:notice] = "See you soon!"
    render :new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  ATTRIBUTE_WHITELIST = [
    :first_name,
    :last_name,
    :email,
    :phone_number,
    :password_confirmation,
    :password
  ]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      ConfirmationSender.send_confirmation_to(@user)
      redirect_to new_confirmation_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(*ATTRIBUTE_WHITELIST)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.haml
%h1 Two Factor Authentication with Twilio

%p Doing two-factor authentication (2FA) at a level of excellence can be tricky. Let's demonstrate how to use the <a href="https://www.twilio.com/">Twilio</a> API to make implementing 2FA a snap.

%p <a href="/users/new">Sign Up</a> or <a href="/sessions/new">Sign In</a> to get started.

app/views/layouts/application.haml
!!!
%html
  %head
    %title SMS 2 Factor Authentication
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1, user-scalable=no'}
    = javascript_include_tag 'application'
    = stylesheet_link_tag '//maxcdn.bootstrapcdn.com/bootswatch/3.3.6/paper/bootstrap.min.css'
    = stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css'
    = stylesheet_link_tag 'application', media: 'all'
    = csrf_meta_tags
  %body
    .navbar.navbar-default.navbar-fixed-top
      .container
        .navbar-header
          %a.navbar-brand(href="/") Control <i class="fa fa-globe"></i> Kaos
          %button.navbar-toggle(type="button"){data: { toggle: "collapse", target: "#navbar-main" }}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
        .navbar-collapse.collapse#navbar-main
          %ul.nav.navbar-nav.navbar-right
            - if authenticated?
              %li
                = link_to "Log Out", logout_path
            - else
              %li
                = link_to "Sign Up", new_user_path
              %li
                = link_to "Sign In", new_session_path

    - if flash[:notice]
      .alert.alert-success.alert-dismissible{ role: "alert" }
        %button.close{ "data-dismiss" => "alert", "aria-label" => "Close"}
          %span{ "aria-hidden" => "true"} &times;
        =flash[:notice]

    - if flash[:error]
      .alert.alert-danger.alert-dismissible{ role: "alert" }
        %button.close{ "data-dismiss" => "alert", "aria-label" => "Close"}
          %span{ "aria-hidden" => "true"} &times;
        =flash[:error]

    .container
      = yield

    %footer.container
      Made with <i class="fa fa-heart"></i> by your pals <a href="http://www.twilio.com">@twilio</a>

    = javascript_include_tag '//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js'

app/views/secrets/index.haml
%h1 Shhh... <small>It's secret for your eyes only</small>

= image_tag "top-secret.jpg"

app/views/users/new.haml
%h1 We're going to be best friends

%p Thanks for your interest in signing up! Can you tell us a bit about yourself?


- @user.errors.full_messages.each do |error|
  %li= error

= form_for @user, html: { class: "form-horizontal" } do |f|
  .form-group
    = f.label :first_name, "First name", class: "col-md-2 control-label"
    .col-sm-10
      = f.text_field :first_name, class: "form-control"
  .form-group
    = f.label :last_name, "Last name", class: "col-md-2 control-label"
    .col-sm-10
      = f.text_field :last_name, class: "form-control"
  .form-group
    = f.label :email, "Email", class: "col-md-2 control-label"
    .col-sm-10
      = f.text_field :email, class: "form-control"
  .form-group
    = f.label :phone_number, "Phone number", class: "col-md-2 control-label"
    .col-sm-10
      = f.text_field :phone_number, class: "form-control"
  .form-group
    = f.label :password, "Password", class: "col-md-2 control-label"
    .col-sm-10
      = f.password_field :password, class: "form-control"
  .form-group
    = f.label :password_confirmation, "Confirm password", class: "col-md-2 control-label"
    .col-sm-10
      = f.password_field :password_confirmation, class: "form-control"

  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit "Sign Up", class: "btn btn-success"